name: Say Hello

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello to Me
        uses: cgironalas/github_actions@v2
        with:
          who-to-greet: "Carlos"
